### ISSUE TITLE
Splitting stopped working

### ISSUE THREAD

**Issue by bengry** [amitmarx/pimp-my-wolt#21]
Seems like the Cibus iframe broke in the last couple of days (worked on Sunday just fine) and now in the Cibus iframe where you split the bill, nothing happens.

**Comment by amitmarx** [comment]
Thank you @bengry, I will look at it this weekend :)

**Comment by amitmarx** [comment]
Hey @bengry ,
I think I fixed the issue.
Can you please let me know if it still breaks from some reason?

**Comment by bengry** [comment]
> Hey @bengry , I think I fixed the issue. Can you please let me know if it still breaks from some reason?

Works fine now, thanks for the quick response time.
