### ISSUE TITLE
Cibus splitting doesn't work

### ISSUE THREAD

**Issue by bengry** [amitmarx/pimp-my-wolt#23]
When I make an order via Wolt and get to the Cibus splitting popup, nothing happens. There's just an infinitely-loading spinner.
The names (Wolt -> Cibus) are mapped correctly, and this extension worked great in the past.

I'm guessing that Cibus changed something in the DOM, but that's just an educated guess.

**Comment by amitmarx** [comment]
Hey Ben, thank you!

Unfortunately, I don't have Cibus access anymore.
Any chance you can export the HTML page and share it with me?

amitmarx@gmail.com

**Comment by bengry** [comment]
Sent. Thanks @amitmarx!

**Comment by amitmarx** [comment]
Hey @bengry,

I believe I found the issue—there were some changes made by Wolt that may have caused the problem. I've released a new version with the fix, so hopefully, everything will work as it used to on Sunday.
If the problem persists, I’d really appreciate it if you could re-open the issue.

Thanks!

**Comment by bengry** [comment]
> I believe I found the issue—there were some changes made by Wolt that may have caused the problem.

I thought the issue would be on Cibus' side, since everything worked fine (mapping included), until the Cibus iframe, where the split wouldn't happen. Is that not the case?

> I've released a new version with the fix, so hopefully, everything will work as it used to on Sunday.

Thanks! ~Is this 1.0.20? Or is it still not updated on the Chrome Web Store?~ Nevermind, saw [here](https://github.com/amitmarx/pimp-my-wolt/commit/a9e221cc00dfcf7edb9a699e73831963c792c05e) that it's 1.0.21, so I'll wait for it to be on the Web Store, hopefully by Sunday. Or I'll sideload it.

> If the problem persists, I’d really appreciate it if you could re-open the issue.

Will do

**Comment by amitmarx** [comment]
It turns out the Cibus change isn't affecting the plugin, I verified that all the query selectors are working properly.
However, on the Wolt side, I noticed they removed some of their data-test-id tags, which the plugin was relying on.
As a result, the plugin couldn't retrieve how much each customer should pay.
This led to an empty list, causing the Cibus part to hang.

Regarding the version, yes, you are right, it will be on 1.0.21 It takes few hours for chrome to update,
but I assume it will get updated by Sunday :)

**Comment by bengry** [comment]
> Regarding the version, yes, you are right, it will be on 1.0.21 It takes few hours for chrome to update,
> but I assume it will get updated by Sunday :)

Unfortunately it didn't work. I tried this just now and it had the same issue as before. I ensured to be on v1.0.21 before making the order.

**Comment by amitmarx** [comment]
Hey sorry it did not work and thank you for letting me know.

I just found two more changes Wolt has done that probably caused it not working.
I impulsively released another fix version but then tested and saw I missed one more place referenced one of this changes.
I fixed that, tested and created a new version (1.0.23).
I did found a way to better test it this time, so I'm more confident this time it will get resolved 🤞

**Comment by bengry** [comment]
> I just found two more changes Wolt has done that probably caused it not working. I impulsively released another fix version but then tested and saw I missed one more place referenced one of this changes. I fixed that, tested and created a new version (1.0.23). I did found a way to better test it this time, so I'm more confident this time it will get resolved 🤞

Works great now, thanks!
