### ISSUE TITLE
The extension isn't wokring anymore

### ISSUE THREAD

**Issue by ItaiYosephi** [amitmarx/pimp-my-wolt#24]
Seeing this error in the console:

![CleanShot 2024-12-08 at 12 01 11@2x](https://github.com/user-attachments/assets/6c0e8719-eaf6-4e8d-939a-7d4a46ffffb4)

**Comment by amitmarx** [comment]
Hey @ItaiYosephi thank you for reporting me.
I'm not using Cibus anymore so I can't check it end to end, though I think I found the issue.
Wolt changed the name of one of the HTML tags I was based on, I fixed it and submitted a new version to Chrome Web Store, hopefully it will be deployed soon.
Can you please let me know if it is still not resolved?

**Comment by ItaiYosephi** [comment]
@amitmarx It worked!
Thanks :)
